### ISSUE TITLE
Not available for Linux arm64?

### ISSUE THREAD

**Issue by darribas** [conda-forge/r-lwgeom-feedstock#51]
### Comment:

I'm trying the following:

```bash
jovyan@3dbbdc80961d:~$ conda create -n test -c conda-forge r-lwgeom
Channels:
 - conda-forge
Platform: linux-aarch64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - r-lwgeom

Current channels:

  - https://conda.anaconda.org/conda-forge

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


jovyan@3dbbdc80961d:~$
```

This behaviour does not reproduce on amd64. Is there a reason why? 

My ultimate goal is to install `tmap`, which relies on `lwgeom`. Any pointers or suggestions? Thank you so much!!!

**Comment by mfansler** [comment]
Thanks for posting an Issue. Feedstocks don't build for linux-aarch64 or linux-ppc64le by default, but instead such builds must be requested. Please see [the documentation on how to do this](https://conda-forge.org/docs/maintainer/knowledge_base/#using-arch_rebuildtxt).

Please let me know if you need further assistance with this!

**Comment by darribas** [comment]
Thanks so much for the super quick response! I _think_ I've done it correctly over at:

https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6118

Is that all required? If so, should I assume at some point it'll become available on the channel?

If I've missed something, I'd really appreciate a bit of guidance, first-timer here!

**Comment by mfansler** [comment]
Yes, looks good, though if you want `r-lwgeom` you can directly request that and all its dependencies will be automatically built as well.

Note that currently there is generally an outage with all builds, so it may be until after the weekend before things get resolved. Otherwise, I will try to keep an eye out for the migration PRs when they come through.

**Comment by darribas** [comment]
The [PR](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6118) seems to have been merged (yay!). However, if I try to create a simple env with `r-tmap`, it fails:

```shell
jovyan@514e0a3b279b:~$ mamba  create -c conda-forge -n test r-tmap

Looking for: ['r-tmap']

conda-forge/noarch                                  15.4MB @  39.0MB/s  0.4s
conda-forge/linux-aarch64                           12.3MB @  23.0MB/s  0.5s
Could not solve for environment specs
The following packages are incompatible
└─ r-tmap is not installable because there are no viable options
   ├─ r-tmap 2.2 would require
   │  └─ r-base >=3.5.1,<3.5.2.0a0 , which does not exist (perhaps a missing channel);
   ├─ r-tmap [2.2|2.3_1|2.3_2|3.0] would require
   │  └─ r-base >=3.5,<3.6.0a0 , which does not exist (perhaps a missing channel);
   ├─ r-tmap 2.2 would require
   │  └─ r-tmaptools >=2.0_1  but there are no viable options
   │     ├─ r-tmaptools 2.0_1 would require
   │     │  └─ r-base >=3.5.1,<3.5.2.0a0 , which does not exist (perhaps a missing channel);
   │     ├─ r-tmaptools [2.0_1|2.0_2|3.0] would require
   │     │  └─ r-base >=3.5,<3.6.0a0 , which does not exist (perhaps a missing channel);
   │     └─ r-tmaptools [2.0_1|2.0_2|3.0|3.1_1] would require
   │        └─ r-lwgeom >=0.1_4 , which does not exist (perhaps a missing channel);
   ├─ r-tmap [2.3_1|2.3_2|3.0] would require
   │  └─ r-lwgeom >=0.1_4 , which does not exist (perhaps a missing channel);
   └─ r-tmap [3.3|3.3_1|3.3_2|3.3_3|3.3_4] would require
      └─ r-lwgeom >=0.2_5 , which does not exist (perhaps a missing channel).
jovyan@514e0a3b279b:~$
```

This seems to still point back to `r-lwgeom` not available. I try also to create an env to see if that is available, but luck either:

```shell
jovyan@514e0a3b279b:~$ mamba  create -c conda-forge -n test r-lwgeom

Looking for: ['r-lwgeom']

conda-forge/linux-aarch64                                   Using cache
conda-forge/noarch                                          Using cache
Could not solve for environment specs
The following package could not be installed
└─ r-lwgeom does not exist (perhaps a typo or a missing channel).
jovyan@514e0a3b279b:~$
```

Any ideas on what I'm missing? Thank you so much in advance!

**Comment by darribas** [comment]
@mfansler , to answer your question, the library I'd like to install is `r-tmap`, not `r-lwgeom` necessarily, but that is a dependency of `r-tmap`. I thought by including `r-tmap`, it'd pull the dependency on `r-lwgeom`, but it does not appear to be the case? Should I add it explicitly to the list for migration? To be clear, the above line works fine on `amd64`.

Thanks so much in advance for your help! :pray:

**Comment by mfansler** [comment]
It works like you expect. However, the PR here to update the recipe has failed: https://github.com/conda-forge/r-lwgeom-feedstock/pull/52. Same goes for the `r-interleave` PR: https://github.com/conda-forge/r-interleave-feedstock/pull/2. Sorry, I haven't had time to debug what is going wrong with them yet.

**Comment by mfansler** [comment]
Maybe found the issue...the `r-geometries` package did not finish building last week. https://github.com/conda-forge/r-geometries-feedstock/runs/26922566964... Hopefully that was the only hold up 🤞

**Comment by darribas** [comment]
Amazing! should that then make it available? I'm currently still seeing the same behaviour but perhaps it takes a while to trickle down to `r-lwgeom` and then `r-tmap`?

**Comment by mfansler** [comment]
Not immediately. That should let me get the stalled ones building, then it takes usually a cycle of 2-4 hours to upload, get indexed, then the bot to recognize that the next downstream feedstocks can receive a PR. I believe the longest chain is `r-tmap -> r-mapdeck -> r-spatialwidget -> r-interleave`. So, maybe not until tomorrow, assuming everything goes through.

**Comment by mfansler** [comment]
FYI, the `r-mapdeck` migration is now merged. Should be a matter of 1-2 hours to get uploaded and indexed. Let me know whether the `r-tmap` solve is then working or not.

**Comment by mfansler** [comment]
This should be resolved now.

**Comment by darribas** [comment]
I can confirm it works, fantastic!!! Thank yo so much for your all help and support to get this over the line.

One question (actually two):

- Just so I don't have to bother you every time I add one package to the migration, is there any way I can read up on how to "track" these packages to see if they go through (a bit like you did and found the issues w/ `r-geometries` and `r-interleave`? I'd be happy to do my homework a bit more next time to move it through myself (I'm likely to be using this way of installing R packages in the future)
- If an R package from CRAN is _not_ available on `conda-forge`, is [this response](https://stackoverflow.com/a/69921221) still current?

Thank you so much for all your time and help!

**Comment by mfansler** [comment]
Glad to help!

1. You can track them on the status page under "Long-running migrations". You often have to sift through several tabs to find stuff, but the holdups are usually already in the "In PR" section. This case with `r-geometries` was rather complicated though. Specifically, a build had crashed after merging and I had to manually restart it. Since that requires write permissions you can't really get around asking a maintainer to help with that. Fortunately R packages are maintained by a team that basically has permissions for the entire R ecosystem, and we're usually pretty responsive. https://conda-forge.org/status

2. Yes, my (merv) answer there with the last part on using `conda_r_skeleton_helper` is still current advice. And the additional automation scripts provided will make it even simpler if you plan to do it often. See the directions at the bottom of the Gist: https://gist.github.com/mfansler/b7b75f73495b940948efa3c1f58827bf. That's what I use about once a week and they really handle most everything, though you often still need to manually adjust the license (GPL3 -> GPL-3.0-only).

Feel free to ping me if something isn't just working or you need a review on an R-related PR.
